### PR TITLE
Enable CORS - Fix to (https://github.com/fern-api/express-starter/issues/11)

### PR DESCRIPTION
**Pull request by Shield01**
Changed the logical OR operator ('||') to a nullish coalescing operator ("??") as it's a safer operator.

Also enabled CORS policy by default.

### CODE REVIEW

**Comment by zachkirsch** [comment]
Sweet, thanks! Can you delete `package-lock.json`?

**Comment by Shield01** [comment]
> Sweet, thanks! Can you delete `package-lock.json`?

Sure, I can.

Do you mind if I ask why?

I thought the whole idea behind a "package-lock.json", is to keep track of the version number of packages that work with a project.

**Comment by zachkirsch** [comment]
We use yarn in this project, so rather than npm's `package-lock.json`, we use yarn's `yarn.lock` as the lockfile.

You can run `yarn` to regenerate the lockfile (although looks like you did already)

**Comment by Shield01** [comment]
> We use yarn in this project, so rather than npm's `package-lock.json`, we use yarn's `yarn.lock` as the lockfile.
> 
> You can run `yarn` to regenerate the lockfile (although looks like you did already)

Oh okay. Thanks for clarifying.
I would run 'yarn' to regenerate the lockfile. I didn't run it before now.

**Comment by zachkirsch** [comment]
Thanks!

**Pull request merged**
